### ISSUE TITLE
依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shuntagami** [shuntagami/furima-29204#10]
# URL
https://furima-29204.herokuapp.com/
# Basic認証のIDとパスワード
id: admin, pass: 2222
# 出品者用のメールアドレスとパスワード
mail: shuntagami2@gmail.com, pass: 
# 購入者用のメールアドレスとパスワード
mail: shuntagami23@gmail.com, pass: 
# 購入用カードの番号・期限・セキュリティコード
番号: 4242424242424242, 期限: 3月23年, セキュリティコード: 123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
